# Generated by Django 4.2.5 on 2024-01-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='audio',
            field=models.FileField(default='BlockDeNotas/fileAudio/default.mp3', upload_to='audios/'),
        ),
    ]
